version: "3.7"
services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./app/mytodo.db:/app/mytodo.db